# Generated by Django 4.0.4 on 2023-06-09 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_ebook'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='eBook',
            new_name='Books',
        ),
    ]
